const tenant1 = {
  fullName: "Carlos Martínez",
  identificationDocument: "ID-123456789",
  birthDate: new Date("1985-06-15"),
  phone: "+34 612 345 678",
  email: "carlos.martinez@email.com",
  additionalAddress: "Calle Ficticia, 2, Madrid, 28001, España",
  leaseStartDate: new Date("2023-01-01"),
  leaseEndDate: new Date("2024-01-01"),
  contractDuration: "Long-term",
  renewalTerms:
    "Automatic renewal for another year unless termination notice is given 30 days in advance.",
  securityDeposit: 1200.0,
  specificClauses: "No pets allowed.",
  rentAmount: 900.0,
  preferredPaymentMethod: "Bank Transfer",
  discountsOrAdjustments:
    "10% discount for payments made before the 5th of each month.",
  tenantUtilities: "Electricity, Water, Gas",
  basicMaintenance:
    "Tenant responsible for minor repairs, such as lightbulb changes.",
  reportedIssues: "No reported issues.",
  pets: "None",
  moveInDate: new Date("2023-01-01"),
  absencePeriods: "None",
  contractModifications: "No changes to contract.",
  satisfactionSurveys: "Very satisfied with the property and services.",
  communicationHistory: "All communications were smooth and on time.",
  incidents: "No incidents reported.",
  emergencyContactName: "Laura Martínez",
  emergencyContactPhone: "+34 634 567 890",
  emergencyContactRelation: "Sister",
  trustedPerson: "None",
  createdAt: new Date("2023-01-01"),
  updatedAt: new Date("2023-01-01"),
};

const tenant2 = {
  fullName: "Ana Gómez",
  identificationDocument: "PASSPORT-987654321",
  birthDate: new Date("1990-08-22"),
  phone: "+34 654 321 987",
  email: "ana.gomez@email.com",
  additionalAddress: null,
  leaseStartDate: new Date("2024-03-01"),
  leaseEndDate: new Date("2025-03-01"),
  contractDuration: "Indefinite",
  renewalTerms: "Tenant may terminate with 60 days' notice.",
  securityDeposit: 1500.0,
  specificClauses: "Tenant allowed to have pets with prior approval.",
  rentAmount: 950.0,
  preferredPaymentMethod: "Credit Card",
  discountsOrAdjustments: null,
  tenantUtilities: "Electricity, Water",
  basicMaintenance:
    "Tenant to notify any maintenance issues, but owner handles most major repairs.",
  reportedIssues: "Occasional water leakage in kitchen.",
  pets: "Dog (approved)",
  moveInDate: new Date("2024-03-01"),
  absencePeriods: "None",
  contractModifications: "None",
  satisfactionSurveys:
    "Generally satisfied, would prefer faster response times for issues.",
  communicationHistory: "Prompt responses to inquiries.",
  incidents: "No significant incidents.",
  emergencyContactName: "Juan Gómez",
  emergencyContactPhone: "+34 912 345 678",
  emergencyContactRelation: "Father",
  trustedPerson: "None",
  createdAt: new Date("2024-03-01"),
  updatedAt: new Date("2024-03-01"),
};

module.exports = { tenant1, tenant2 };
